/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sampleprogram;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 *
 * @author William
 */
public class MathMLParserTest {

    /**
     * Test of getMathMLFromXMLString method, of class MathMLParser.
     */
    @Test
    public void testGetMathMLFromXMLString() {

        String inputString = "<queryresult success='true'\n"
                + "    error='false'\n"
                + "    numpods='4'\n"
                + "    datatypes=''\n"
                + "    timedout=''\n"
                + "    timedoutpods=''\n"
                + "    timing='1.508'\n"
                + "    parsetiming='0.663'\n"
                + "    parsetimedout='false'\n"
                + "    recalculate=''\n"
                + "    id='MSPa18581c655ed6hbe5h3b700001dh88bh2b2f3b9h2'\n"
                + "    host='http://www4b.wolframalpha.com'\n"
                + "    server='61'\n"
                + "    related='http://www4b.wolframalpha.com/api/v2/relatedQueries.jsp?id=MSPa18591c655ed6hbe5h3b700002464965b19f11cge3708816990573474235'\n"
                + "    version='2.6'>\n"
                + " <pod title='Definite integral'\n"
                + "     scanner='Integral'\n"
                + "     id='Input'\n"
                + "     position='100'\n"
                + "     error='false'\n"
                + "     numsubpods='1'\n"
                + "     primary='true'>\n"
                + "  <subpod title=''>\n"
                + "   <mathml>\n"
                + "    <math xmlns='http://www.w3.org/1998/Math/MathML'\n"
                + "        mathematica:form='StandardForm'\n"
                + "        xmlns:mathematica='http://www.wolfram.com/XML/'>\n"
                + "     <mrow>\n"
                + "      <mrow>\n"
                + "       <msubsup>\n"
                + "        <mo>?</mo>\n"
                + "        <mn>0</mn>\n"
                + "        <mn>3</mn>\n"
                + "       </msubsup>\n"
                + "       <mrow>\n"
                + "        <msup>\n"
                + "         <mi>x</mi>\n"
                + "         <mn>3</mn>\n"
                + "        </msup>\n"
                + "        <mo>?</mo>\n"
                + "        <mrow>\n"
                + "         <mi>d</mi>\n"
                + "         <mo>?</mo>\n"
                + "         <mi>x</mi>\n"
                + "        </mrow>\n"
                + "       </mrow>\n"
                + "      </mrow>\n"
                + "      <mo>=</mo>\n"
                + "      <mrow>\n"
                + "       <mfrac>\n"
                + "        <mn>81</mn>\n"
                + "        <mn>4</mn>\n"
                + "       </mfrac>\n"
                + "       <mtext>~</mtext>\n"
                + "       <mn>20.25</mn>\n"
                + "      </mrow>\n"
                + "     </mrow>\n"
                + "    </math>\n"
                + "   </mathml>\n"
                + "  </subpod>\n"
                + "  <states count='2'>\n"
                + "   <state name='More digits'\n"
                + "       input='Input__More digits' />\n"
                + "   <state name='Step-by-step solution'\n"
                + "       input='Input__Step-by-step solution' />\n"
                + "  </states>\n"
                + " </pod>\n"
                + " <pod title='Visual representation of the integral'\n"
                + "     scanner='Integral'\n"
                + "     id='VisualRepresentationOfTheIntegral'\n"
                + "     position='200'\n"
                + "     error='false'\n"
                + "     numsubpods='1'>\n"
                + "  <subpod title='' />\n"
                + " </pod>\n"
                + " <pod title='Riemann sums'\n"
                + "     scanner='Integral'\n"
                + "     id='RiemannSums'\n"
                + "     position='300'\n"
                + "     error='false'\n"
                + "     numsubpods='1'>\n"
                + "  <subpod title='' />\n"
                + "  <states count='1'>\n"
                + "   <state name='More cases'\n"
                + "       input='RiemannSums__More cases' />\n"
                + "  </states>\n"
                + " </pod>\n"
                + " <pod title='Indefinite integral'\n"
                + "     scanner='Integral'\n"
                + "     id='IndefiniteIntegral'\n"
                + "     position='400'\n"
                + "     error='false'\n"
                + "     numsubpods='1'>\n"
                + "  <subpod title=''>\n"
                + "   <mathml>\n"
                + "    <math xmlns='http://www.w3.org/1998/Math/MathML'\n"
                + "        mathematica:form='StandardForm'\n"
                + "        xmlns:mathematica='http://www.wolfram.com/XML/'>\n"
                + "     <mrow>\n"
                + "      <mrow>\n"
                + "       <mo>?</mo>\n"
                + "       <mrow>\n"
                + "        <msup>\n"
                + "         <mi>x</mi>\n"
                + "         <mn>3</mn>\n"
                + "        </msup>\n"
                + "        <mo>?</mo>\n"
                + "        <mrow>\n"
                + "         <mi>d</mi>\n"
                + "         <mo>?</mo>\n"
                + "         <mi>x</mi>\n"
                + "        </mrow>\n"
                + "       </mrow>\n"
                + "      </mrow>\n"
                + "      <mo>=</mo>\n"
                + "      <mrow>\n"
                + "       <mfrac>\n"
                + "        <msup>\n"
                + "         <mi>x</mi>\n"
                + "         <mn>4</mn>\n"
                + "        </msup>\n"
                + "        <mn>4</mn>\n"
                + "       </mfrac>\n"
                + "       <mo>+</mo>\n"
                + "       <mi>constant</mi>\n"
                + "      </mrow>\n"
                + "     </mrow>\n"
                + "    </math>\n"
                + "   </mathml>\n"
                + "  </subpod>\n"
                + "  <states count='1'>\n"
                + "   <state name='Step-by-step solution'\n"
                + "       input='IndefiniteIntegral__Step-by-step solution' />\n"
                + "  </states>\n"
                + " </pod>\n"
                + "</queryresult>";

        String expectedResult = "<mathml>\n"
                + "    <math xmlns='http://www.w3.org/1998/Math/MathML'\n"
                + "        mathematica:form='StandardForm'\n"
                + "        xmlns:mathematica='http://www.wolfram.com/XML/'>\n"
                + "     <mrow>\n"
                + "      <mrow>\n"
                + "       <msubsup>\n"
                + "        <mo>?</mo>\n"
                + "        <mn>0</mn>\n"
                + "        <mn>3</mn>\n"
                + "       </msubsup>\n"
                + "       <mrow>\n"
                + "        <msup>\n"
                + "         <mi>x</mi>\n"
                + "         <mn>3</mn>\n"
                + "        </msup>\n"
                + "        <mo>?</mo>\n"
                + "        <mrow>\n"
                + "         <mi>d</mi>\n"
                + "         <mo>?</mo>\n"
                + "         <mi>x</mi>\n"
                + "        </mrow>\n"
                + "       </mrow>\n"
                + "      </mrow>\n"
                + "      <mo>=</mo>\n"
                + "      <mrow>\n"
                + "       <mfrac>\n"
                + "        <mn>81</mn>\n"
                + "        <mn>4</mn>\n"
                + "       </mfrac>\n"
                + "       <mtext>~</mtext>\n"
                + "       <mn>20.25</mn>\n"
                + "      </mrow>\n"
                + "     </mrow>\n"
                + "    </math>\n"
                + "   </mathml>\n"
                + "  </subpod>\n"
                + "  <states count='2'>\n"
                + "   <state name='More digits'\n"
                + "       input='Input__More digits' />\n"
                + "   <state name='Step-by-step solution'\n"
                + "       input='Input__Step-by-step solution' />\n"
                + "  </states>\n"
                + " </pod>\n"
                + " <pod title='Visual representation of the integral'\n"
                + "     scanner='Integral'\n"
                + "     id='VisualRepresentationOfTheIntegral'\n"
                + "     position='200'\n"
                + "     error='false'\n"
                + "     numsubpods='1'>\n"
                + "  <subpod title='' />\n"
                + " </pod>\n"
                + " <pod title='Riemann sums'\n"
                + "     scanner='Integral'\n"
                + "     id='RiemannSums'\n"
                + "     position='300'\n"
                + "     error='false'\n"
                + "     numsubpods='1'>\n"
                + "  <subpod title='' />\n"
                + "  <states count='1'>\n"
                + "   <state name='More cases'\n"
                + "       input='RiemannSums__More cases' />\n"
                + "  </states>\n"
                + " </pod>\n"
                + " <pod title='Indefinite integral'\n"
                + "     scanner='Integral'\n"
                + "     id='IndefiniteIntegral'\n"
                + "     position='400'\n"
                + "     error='false'\n"
                + "     numsubpods='1'>\n"
                + "  <subpod title=''>\n"
                + "   <mathml>\n"
                + "    <math xmlns='http://www.w3.org/1998/Math/MathML'\n"
                + "        mathematica:form='StandardForm'\n"
                + "        xmlns:mathematica='http://www.wolfram.com/XML/'>\n"
                + "     <mrow>\n"
                + "      <mrow>\n"
                + "       <mo>?</mo>\n"
                + "       <mrow>\n"
                + "        <msup>\n"
                + "         <mi>x</mi>\n"
                + "         <mn>3</mn>\n"
                + "        </msup>\n"
                + "        <mo>?</mo>\n"
                + "        <mrow>\n"
                + "         <mi>d</mi>\n"
                + "         <mo>?</mo>\n"
                + "         <mi>x</mi>\n"
                + "        </mrow>\n"
                + "       </mrow>\n"
                + "      </mrow>\n"
                + "      <mo>=</mo>\n"
                + "      <mrow>\n"
                + "       <mfrac>\n"
                + "        <msup>\n"
                + "         <mi>x</mi>\n"
                + "         <mn>4</mn>\n"
                + "        </msup>\n"
                + "        <mn>4</mn>\n"
                + "       </mfrac>\n"
                + "       <mo>+</mo>\n"
                + "       <mi>constant</mi>\n"
                + "      </mrow>\n"
                + "     </mrow>\n"
                + "    </math>\n"
                + "   </mathml>";
        System.out.println("getMathMLFromXMLString");
        MathMLParser instance = new MathMLParser();
        String result = instance.getMathMLFromXMLString(inputString);
        assertEquals(expectedResult, result);
    }

}
